version: '3.4'

services:
  postgres:
    image: postgres
    restart: always
    shm_size: 1g

    env_file:
      - deploy.env
    ports:
      - "5433:5432"

  backend:
    build:
      context: ./backend/
      dockerfile: ./Dockerfile

    restart: always
    env_file:
      - deploy.env
    depends_on:
      - postgres
    volumes:
      - ./backend_logs/:/backend/logs/
    ports:
      - "80:8989"