version: '3.4'

services:
  postgres:
    image: postgres
    restart: always
    shm_size: 1g

    env_file:
      - deploy.env

  backend:
    build:
      context: ./backend/
      dockerfile: ./Dockerfile

    restart: always
    env_file:
      - deploy.env
    depends_on:
      - postgres

  nginx:
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile

    restart: always
    env_file:
      - deploy.env
    depends_on:
      - backend
    ports:
      - "8888:80"

