version: '3.1'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

#    ports:
#      - "5432:5432"

  api:
    build:
      context: ..

    depends_on:
      - postgres

    ports:
      - "9797:8000"

